# Generated by Django 4.0.5 on 2022-06-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(max_length=120, unique=True)),
                ('employee_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scadual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('pr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_time.employee', to_field='employee_id')),
            ],
        ),
    ]
