# Generated by Django 4.0.5 on 2022-06-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_time', '0002_employee_scadual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scadual',
            new_name='Schedule',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(unique=True),
        ),
    ]
